"""adding location

Revision ID: 25b79c8425b2
Revises: fe0e8468380c
Create Date: 2026-09-28 08:40:43.330961

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b79c8425b2'
down_revision: Union[str, Sequence[str], None] = 'fe0e8468380c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('servicable_location',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partner.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'location_id')
    )
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('delivery_partner', 'servicable_zip_codes')
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('servicable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('servicable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
