"""adding shipment event

Revision ID: 3ca706e4102f
Revises: 4c72d8d7be2a
Create Date: 2026-09-14 23:23:13.868097

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ca706e4102f'
down_revision: Union[str, Sequence[str], None] = '4c72d8d7be2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.drop_column('shipment', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_column('seller', 'zip_code')
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
