"""adding review

Revision ID: ccaeb0d6a292
Revises: 7d74d8481d0d
Create Date: 2026-09-20 20:34:41.843690

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccaeb0d6a292'
down_revision: Union[str, Sequence[str], None] = '7d74d8481d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('review')
    # ### end Alembic commands ###
